# Generated by Django 5.0.3 on 2024-04-03 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products_detail',
            new_name='Products',
        ),
    ]
